# Generated by Django 3.2.4 on 2021-06-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', '男性'), ('F', '女性'), ('O', 'その他')], max_length=10)),
            ],
        ),
    ]
