# Generated by Django 3.2.4 on 2021-06-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', '男性'), ('Female', '女性'), ('Other', 'その他')], max_length=10),
        ),
    ]
